name: covid_statistic
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.0.0
  http: ^0.12.0
  meta: ^1.1.6
  equatable: ^1.0.0
  intl: ^0.15.8
  animations: ^1.1.2
  google_maps_flutter: ^1.2.0
  location: ^3.0.0
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test_coverage: ^0.4.0
  bloc_test: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Medium.ttf
